apiVersion: apps/v1
kind: Deployment
metadata:
  name: pjgl-config-server
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: pjgl-config-server
  template:
    metadata:
      labels:
        app: pjgl-config-server
    spec:
      containers:
      - name: pjgl-config-server
        image: pguevarl/config-server:latest # Replace with your actual image
        ports:
        - containerPort: 8085
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pjgl-config-server
spec:
  selector:
    app: pjgl-config-server
  type: LoadBalancer # Or NodePort if preferred
  ports:
  - port: 8085 # External port
    targetPort: 8085 # Container port
    name: http
