apiVersion: v1
kind: Service
metadata:
  name: grafana-lb-services
spec:
  type: LoadBalancer
  selector:
    app: grafana  # Ensure consistency with deployment labels
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
