apiVersion: v1
kind: Service
metadata:
  name: grafana-lb-services
spec:
  type: LoadBalancer
  selector:
    matchLabels:
      app: grafana
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
