Installing kubectl...
Installing Helm...
Installing Minikube...

Git Semantic Version:
https://github.com/marketplace/actions/git-semantic-version

Comandos Docker:
Listar todos los contenedores con sus direcciones IP:
docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)

Detener todos los contenedores en ejecución:
docker stop $(docker ps -aq)

Eliminar todos los contenedores:
docker rm $(docker ps -aq)

Eliminar todas las imagenes docker:
docker rmi $(docker images -aq)

Versión de minikube:
minikube version

El flag --build asegura que Docker Compose reconstruya las imágenes de los servicios antes de iniciar los contenedores.:
docker-compose up --build

---
Kubernetes en linux:
https://cursosdedesarrollo.com/2020/07/instalacion-de-kubernetes-minikube-en-ubuntu-20-04/
---
Explorar que tiene mi imagen docker:
$ docker container run -d pguevarl/config-server:
bd50b418618ba2fa816d82c9fb437ae6446d0878fde165e7b884bd31bfe1db93
$ docker exec -it bd5 /bin/sh:
$ ls:

Si deseo borrar un buildx en especifico, primero debo usar un buildx diferente y despues ejecutar:
docker buildx rm mybuilder